server :
 servlet : 
  context-path: /credy/api
spring:
  h2:
    console: 
      enabled: true
      path: /h2  
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
